/*
 *  Author: Mike Atkinson
 *
 *  This software has been developed under the copyleft
 *  rules of the GNU General Public License.  Please
 *  consult the GNU General Public License for more
 *  details about use and distribution of this software.
 */
package org.acm.seguin.parser;

import org.acm.seguin.parser.ast.*;
import org.acm.seguin.parser.io.*;


/* Generated By:JJTree: Do not edit this line. JavaParserTreeConstants.java */

public interface JavaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTPACKAGEDECLARATION = 1;
  public int JJTIMPORTDECLARATION = 2;
  public int JJTTYPEDECLARATION = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTUNMODIFIEDCLASSDECLARATION = 5;
  public int JJTATTRIBUTE = 6;
  public int JJTTYPEPARAMETERS = 7;
  public int JJTTYPEPARAMETERLIST = 8;
  public int JJTTYPEPARAMETER = 9;
  public int JJTREFERENCETYPELIST = 10;
  public int JJTREFERENCEVARIANCE = 11;
  public int JJTCLASSBODY = 12;
  public int JJTNESTEDCLASSDECLARATION = 13;
  public int JJTCLASSBODYDECLARATION = 14;
  public int JJTENUMDECLARATION = 15;
  public int JJTIDENTIFIER = 16;
  public int JJTENUMELEMENT = 17;
  public int JJTMETHODDECLARATIONLOOKAHEAD = 18;
  public int JJTINTERFACEDECLARATION = 19;
  public int JJTNESTEDINTERFACEDECLARATION = 20;
  public int JJTUNMODIFIEDINTERFACEDECLARATION = 21;
  public int JJTINTERFACEBODY = 22;
  public int JJTINTERFACEMEMBERDECLARATION = 23;
  public int JJTFIELDDECLARATION = 24;
  public int JJTVARIABLEDECLARATOR = 25;
  public int JJTVARIABLEDECLARATORID = 26;
  public int JJTVARIANCE = 27;
  public int JJTVARIABLEINITIALIZER = 28;
  public int JJTARRAYINITIALIZER = 29;
  public int JJTMETHODDECLARATION = 30;
  public int JJTMETHODDECLARATOR = 31;
  public int JJTFORMALPARAMETERS = 32;
  public int JJTFORMALPARAMETER = 33;
  public int JJTCONSTRUCTORDECLARATION = 34;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 35;
  public int JJTINITIALIZER = 36;
  public int JJTTYPE = 37;
  public int JJTREFERENCETYPE = 38;
  public int JJTTYPEARGUMENTS = 39;
  public int JJTPRIMITIVETYPE = 40;
  public int JJTRESULTTYPE = 41;
  public int JJTNAME = 42;
  public int JJTNAMELIST = 43;
  public int JJTGENERICNAMELIST = 44;
  public int JJTEXPRESSION = 45;
  public int JJTASSIGNMENTOPERATOR = 46;
  public int JJTCONDITIONALEXPRESSION = 47;
  public int JJTCONDITIONALOREXPRESSION = 48;
  public int JJTCONDITIONALANDEXPRESSION = 49;
  public int JJTINCLUSIVEOREXPRESSION = 50;
  public int JJTEXCLUSIVEOREXPRESSION = 51;
  public int JJTANDEXPRESSION = 52;
  public int JJTEQUALITYEXPRESSION = 53;
  public int JJTINSTANCEOFEXPRESSION = 54;
  public int JJTRELATIONALEXPRESSION = 55;
  public int JJTSHIFTEXPRESSION = 56;
  public int JJTADDITIVEEXPRESSION = 57;
  public int JJTMULTIPLICATIVEEXPRESSION = 58;
  public int JJTUNARYEXPRESSION = 59;
  public int JJTPREINCREMENTEXPRESSION = 60;
  public int JJTPREDECREMENTEXPRESSION = 61;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 62;
  public int JJTCASTLOOKAHEAD = 63;
  public int JJTPOSTFIXEXPRESSION = 64;
  public int JJTCASTEXPRESSION = 65;
  public int JJTPRIMARYEXPRESSION = 66;
  public int JJTPRIMARYPREFIX = 67;
  public int JJTPRIMARYSUFFIX = 68;
  public int JJTLITERAL = 69;
  public int JJTBOOLEANLITERAL = 70;
  public int JJTNULLLITERAL = 71;
  public int JJTARGUMENTS = 72;
  public int JJTARGUMENTLIST = 73;
  public int JJTALLOCATIONEXPRESSION = 74;
  public int JJTARRAYDIMSANDINITS = 75;
  public int JJTSTATEMENT = 76;
  public int JJTLABELEDSTATEMENT = 77;
  public int JJTBLOCK = 78;
  public int JJTBLOCKSTATEMENT = 79;
  public int JJTLOCALVARIABLEDECLARATION = 80;
  public int JJTEMPTYSTATEMENT = 81;
  public int JJTSTATEMENTEXPRESSION = 82;
  public int JJTSWITCHSTATEMENT = 83;
  public int JJTSWITCHLABEL = 84;
  public int JJTIFSTATEMENT = 85;
  public int JJTWHILESTATEMENT = 86;
  public int JJTDOSTATEMENT = 87;
  public int JJTFORSTATEMENT = 88;
  public int JJTFORINIT = 89;
  public int JJTSTATEMENTEXPRESSIONLIST = 90;
  public int JJTFORUPDATE = 91;
  public int JJTBREAKSTATEMENT = 92;
  public int JJTCONTINUESTATEMENT = 93;
  public int JJTRETURNSTATEMENT = 94;
  public int JJTTHROWSTATEMENT = 95;
  public int JJTSYNCHRONIZEDSTATEMENT = 96;
  public int JJTTRYSTATEMENT = 97;
  public int JJTASSERTIONSTATEMENT = 98;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "PackageDeclaration",
    "ImportDeclaration",
    "TypeDeclaration",
    "ClassDeclaration",
    "UnmodifiedClassDeclaration",
    "Attribute",
    "TypeParameters",
    "TypeParameterList",
    "TypeParameter",
    "ReferenceTypeList",
    "ReferenceVariance",
    "ClassBody",
    "NestedClassDeclaration",
    "ClassBodyDeclaration",
    "EnumDeclaration",
    "Identifier",
    "EnumElement",
    "MethodDeclarationLookahead",
    "InterfaceDeclaration",
    "NestedInterfaceDeclaration",
    "UnmodifiedInterfaceDeclaration",
    "InterfaceBody",
    "InterfaceMemberDeclaration",
    "FieldDeclaration",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "Variance",
    "VariableInitializer",
    "ArrayInitializer",
    "MethodDeclaration",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "Initializer",
    "Type",
    "ReferenceType",
    "TypeArguments",
    "PrimitiveType",
    "ResultType",
    "Name",
    "NameList",
    "GenericNameList",
    "Expression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "InstanceOfExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PreIncrementExpression",
    "PreDecrementExpression",
    "UnaryExpressionNotPlusMinus",
    "CastLookahead",
    "PostfixExpression",
    "CastExpression",
    "PrimaryExpression",
    "PrimaryPrefix",
    "PrimarySuffix",
    "Literal",
    "BooleanLiteral",
    "NullLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "ArrayDimsAndInits",
    "Statement",
    "LabeledStatement",
    "Block",
    "BlockStatement",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchLabel",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForInit",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "SynchronizedStatement",
    "TryStatement",
    "AssertionStatement",
  };
}
