/*
 *  Author: Mike Atkinson
 *
 *  This software has been developed under the copyleft
 *  rules of the GNU General Public License.  Please
 *  consult the GNU General Public License for more
 *  details about use and distribution of this software.
 */
package org.acm.seguin.parser;

import org.acm.seguin.parser.ast.*;
import org.acm.seguin.parser.io.*;


/* Generated By:JJTree&JavaCC: Do not edit this line. JavaParserConstants.java */
public interface JavaParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 11;
  int FORMAL_COMMENT = 12;
  int MULTI_LINE_COMMENT = 13;
  int CATEGORY_COMMENT = 14;
  int ABSTRACT = 16;
  int BOOLEAN = 17;
  int BREAK = 18;
  int BYTE = 19;
  int CASE = 20;
  int CATCH = 21;
  int CHAR = 22;
  int CLASS = 23;
  int CONST = 24;
  int CONTINUE = 25;
  int _DEFAULT = 26;
  int DO = 27;
  int DOUBLE = 28;
  int ELSE = 29;
  int EXTENDS = 30;
  int FALSE = 31;
  int FINAL = 32;
  int FINALLY = 33;
  int FLOAT = 34;
  int FOR = 35;
  int GOTO = 36;
  int IF = 37;
  int IMPLEMENTS = 38;
  int IMPORT = 39;
  int INSTANCEOF = 40;
  int INT = 41;
  int INTERFACE = 42;
  int LONG = 43;
  int NATIVE = 44;
  int NEW = 45;
  int NULL = 46;
  int PACKAGE = 47;
  int PRIVATE = 48;
  int PROTECTED = 49;
  int PUBLIC = 50;
  int RETURN = 51;
  int SHORT = 52;
  int STATIC = 53;
  int STRICTFP = 54;
  int SUPER = 55;
  int SWITCH = 56;
  int SYNCHRONIZED = 57;
  int THIS = 58;
  int THROW = 59;
  int THROWS = 60;
  int TRANSIENT = 61;
  int TRUE = 62;
  int TRY = 63;
  int VOID = 64;
  int VOLATILE = 65;
  int WHILE = 66;
  int INTEGER_LITERAL = 67;
  int DECIMAL_LITERAL = 68;
  int HEX_LITERAL = 69;
  int OCTAL_LITERAL = 70;
  int FLOATING_POINT_LITERAL = 71;
  int EXPONENT = 72;
  int CHARACTER_LITERAL = 73;
  int STRING_LITERAL = 74;
  int IDENTIFIER = 75;
  int LETTER = 76;
  int DIGIT = 77;
  int LPAREN = 78;
  int RPAREN = 79;
  int LBRACE = 80;
  int RBRACE = 81;
  int LBRACKET = 82;
  int RBRACKET = 83;
  int SEMICOLON = 84;
  int COMMA = 85;
  int DOT = 86;
  int VARARG = 87;
  int ASSIGN = 88;
  int GT = 89;
  int LT = 90;
  int BANG = 91;
  int TILDE = 92;
  int HOOK = 93;
  int COLON = 94;
  int EQ = 95;
  int LE = 96;
  int GE = 97;
  int NE = 98;
  int SC_OR = 99;
  int SC_AND = 100;
  int INCR = 101;
  int DECR = 102;
  int PLUS = 103;
  int MINUS = 104;
  int STAR = 105;
  int SLASH = 106;
  int BIT_AND = 107;
  int BIT_OR = 108;
  int XOR = 109;
  int REM = 110;
  int LSHIFT = 111;
  int RSIGNEDSHIFT = 112;
  int RUNSIGNEDSHIFT = 113;
  int PLUSASSIGN = 114;
  int MINUSASSIGN = 115;
  int STARASSIGN = 116;
  int SLASHASSIGN = 117;
  int ANDASSIGN = 118;
  int ORASSIGN = 119;
  int XORASSIGN = 120;
  int REMASSIGN = 121;
  int LSHIFTASSIGN = 122;
  int RSIGNEDSHIFTASSIGN = 123;
  int RUNSIGNEDSHIFTASSIGN = 124;
  int ATTRIBUTE = 125;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;
  int IN_CATEGORY_COMMENT = 4;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"//\"",
    "<token of kind 8>",
    "\"/*\"",
    "\"/*<\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 15>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"...\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"@\"",
  };

}
