/*
 *  Author: Mike Atkinson
 *
 *  This software has been developed under the copyleft
 *  rules of the GNU General Public License.  Please
 *  consult the GNU General Public License for more
 *  details about use and distribution of this software.
 */
package org.acm.seguin.parser.ast;

import org.acm.seguin.parser.JavaParserVisitor;
import org.acm.seguin.parser.JavaParser;
import org.acm.seguin.pretty.ModifierHolder;
import org.acm.seguin.pretty.JavaDocComponent;
import org.acm.seguin.pretty.JavaDocable;
import org.acm.seguin.pretty.JavaDocableImpl;
import org.acm.seguin.pretty.PrintData;
import org.acm.seguin.pretty.ForceJavadocComments;
import org.acm.seguin.pretty.ai.RequiredTags;


import org.acm.seguin.util.FileSettings;
import org.acm.seguin.pretty.DescriptionPadder;
/* Generated By:JJTree: Do not edit this line. ASTEnumDeclaration.java */

public class ASTEnumDeclaration extends SimpleNode {
    // Instance Variables
    private ModifierHolder modifiers;
    private JavaDocableImpl jdi;
    
    
  public ASTEnumDeclaration(int id) {
    super(id);
    modifiers = new ModifierHolder();
    jdi = new JavaDocableImpl();
  }

  public ASTEnumDeclaration(JavaParser p, int id) {
    super(p, id);
    modifiers = new ModifierHolder();
    jdi = new JavaDocableImpl();
  }



    
    /**
     *  Determine if the object is final
     *
     *@return    true if this stores an FINAL flag
     */
    public boolean isFinal() {
        return modifiers.isFinal();
    }
    
    
    /**
     *  Determine if the object is private
     *
     *@return    true if this stores an PRIVATE flag
     */
    public boolean isPrivate() {
        return modifiers.isPrivate();
    }
    
    
    /**
     *  Determine if the object is protected
     *
     *@return    true if this stores an PROTECTED flag
     */
    public boolean isProtected() {
        return modifiers.isProtected();
    }
    
    
    /**
     *  Determine if the object is public
     *
     *@return    true if this stores an PUBLIC flag
     */
    public boolean isPublic() {
        return modifiers.isPublic();
    }
    
    
    /**
     *  Determine if the object is static
     *
     *@return    true if this stores an static flag
     */
    public boolean isStatic() {
        return modifiers.isStatic();
    }
    
    
    
    /**
     *  Returns a string containing all the modifiers
     *
     *@param code the code used to determine the order of the modifiers
     *@return    the string representationof the order
     */
    public String getModifiersString(int code) {
        if (code == PrintData.ALPHABETICAL_ORDER)
            return modifiers.toString();
        else
            return modifiers.toStandardOrderString();
    }
    
    
    /**
     *  Returns the modifier holder
     *
     *@return    the holder
     */
    public ModifierHolder getModifiers() {
        return modifiers;
    }
    
    
    /**
     *  Checks to see if it was printed
     *
     *@return    true if it still needs to be printed
     */
    public boolean isRequired() {
        ForceJavadocComments fjc = new ForceJavadocComments();
        return jdi.isRequired() && fjc.isJavaDocRequired("field", modifiers);
    }
    
    
    /**
     *  Adds a modifier to a class
     *
     *@param  modifier  the next modifier
     */
    public void addModifier(String modifier) {
        modifiers.add(modifier);
    }
    
    
    /**
     *  Convert this object to a string
     *
     *@return    a string representing this object
     */
    public String toString() {
        return super.toString() + " [" + getModifiersString(PrintData.ALPHABETICAL_ORDER) + "]";
    }
    
    
    
    /**
     *  Allows you to add a java doc component
     *
     *@param  component  the component that can be added
     */
    public void addJavaDocComponent(JavaDocComponent component) {
        jdi.addJavaDocComponent(component);
    }
    
    
    /**
     *  Prints all the java doc components
     *
     *@param  printData  the print data
     */
    public void printJavaDocComponents(PrintData printData) {
        FileSettings bundle = FileSettings.getSettings("Refactory", "pretty");
        jdi.printJavaDocComponents(printData, bundle.getString("enum.tags"));
    }
    
    
    /**
     *  Makes sure all the java doc components are present
     */
    public void finish() {
        FileSettings bundle = FileSettings.getSettings("Refactory", "pretty");   //  Get the resource bundle
        jdi.require("", DescriptionPadder.find(bundle, "enum.descr"));           //  Description of the field
        ASTLiteral id = (ASTLiteral) jjtGetChild(1);                             //  Require the other tags
        RequiredTags.getTagger().addTags(bundle, "enum", id.getName(), jdi);
    }

  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
