/*
 *Author: Mike Atkinson
 *
 *This software has been developed under the copyleft
 *rules of the GNU General Public License.  Please
 *consult the GNU General Public License for more
 *details about use and distribution of this software.
 */
package org.acm.seguin.parser.ast;

import org.acm.seguin.parser.JavaParserVisitor;
import org.acm.seguin.parser.JavaParserTreeConstants;
import org.acm.seguin.parser.Node;
import org.acm.seguin.parser.NamedToken;
import org.acm.seguin.parser.JavaParser;
import org.acm.seguin.parser.Token;
import java.util.*;

/*
 *Generated By:JJTree: Do not edit this line. ASTReferenceType.java
 */
/**
 *Description of the Class
 *
 * @author  Mike Atkinson
 */
public class ASTReferenceType extends ASTType {
    //  Instance Variable
    private int arrayCount;
    /**
     *Constructor for the ASTReferenceType object
     *
     * @paramid  Description of Parameter
     */
    public ASTReferenceType(int id) {
        super(id);
    }

    /**
     *Constructor for the ASTReferenceType object
     *
     * @paramp   Description of Parameter
     * @paramid  Description of Parameter
     */
    public ASTReferenceType(JavaParser p, int id) {
        super(p, id);
    }

    /**
     *  Set the number of indirection for the array
     *
     * @paramcount  the count
     */
    public void setArrayCount(int count) {
        arrayCount = count;
    }

    /**
     *  Get the number of indirection for the array
     *
     * @return  the count
     */
    public int getArrayCount() {
        return arrayCount;
    }

/*
    public String getImage() {
        if (jjtGetNumChildren()>0) {
            String x = ((SimpleNode)jjtGetFirstChild()).getName();
            for (int i=0; i<arrayCount; i++) {
                x = x + "[]";
            }
            return x;
        } else {
            return "";
        }
    }
*/    
    
    /**
     * Accept the visitor. *
     *
     * @paramvisitor  Description of Parameter
     * @paramdata     Description of Parameter
     * @return        Description of the Returned Value
     */
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}

